server:
    port: 8080
spring:
    application:
        name: anglo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/scsdbnew
        username: root
    jpa:
        hibernate:
            ddl-auto: update
    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher
    security:
        user:
            name: '"Alice"'
            password: '"Alice123"'