server:
    port: 8081
spring:
    application:
        name: anglo
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/scsdbtest
        username: root
    jpa:
        hibernate:
            ddl-auto: update